### ISSUE TITLE
如何解决解码错误的问题？

### ISSUE THREAD

**Issue by popeyesheng** [danfengcao/binlog2sql#109]
Traceback (most recent call last):
  File "binlog2sql.py", line 150, in <module>
    binlog2sql.process_binlog()
  File "binlog2sql.py", line 74, in process_binlog
    for binlog_event in stream:
  File "/usr/local/lib/python3.6/site-packages/pymysqlreplication/binlogstream.py", line 432, in fetchone
    self.__fail_on_table_metadata_unavailable)
  File "/usr/local/lib/python3.6/site-packages/pymysqlreplication/packet.py", line 139, in __init__
    fail_on_table_metadata_unavailable=fail_on_table_metadata_unavailable)
  File "/usr/local/lib/python3.6/site-packages/pymysqlreplication/event.py", line 175, in __init__
    - self.schema_length - 1).decode("utf-8")

**Comment by v587xpt** [comment]
在使用 -B 转为恢复sql时，也遇到了编码的问题，请问您解决了吗？
`Traceback (most recent call last):
  File "binlog2sql.py", line 150, in <module>
    binlog2sql.process_binlog()
  File "binlog2sql.py", line 121, in process_binlog
    self.print_rollback_sql(filename=tmp_file)
  File "binlog2sql.py", line 129, in print_rollback_sql
    for line in reversed_lines(f_tmp):
  File "/home/system_tool/binlog_recover/binlog2sql/binlog2sql/binlog2sql_util.py", line 249, in reversed_lines
    block = block.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte`

**Comment by v587xpt** [comment]
已经解决了；
修改 binlog2sql_util.py 第249行：block = block.decode("utf-8", 'ignore')；

**Comment by realcp1018** [comment]
> 已经解决了； 修改 binlog2sql_util.py 第249行：block = block.decode("utf-8", 'ignore')；

不要用errors='ignore'，会导致数据丢失的，建议使用python2运行此工具
