### ISSUE TITLE
生成回滚sql报错：UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 0: invalid start byte

### ISSUE THREAD

**Issue by lengmianshi** [danfengcao/binlog2sql#119]
mysql8 下做生成回滚sql出错：
```python
Traceback (most recent call last):
  File "/home/xxx/binlog2sql/binlog2sql/binlog2sql.py", line 150, in <module>
    binlog2sql.process_binlog()
  File "/home/xxx/binlog2sql/binlog2sql/binlog2sql.py", line 121, in process_binlog
    self.print_rollback_sql(filename=tmp_file)
  File "/home/xxx/binlog2sql/binlog2sql/binlog2sql.py", line 129, in print_rollback_sql
    for line in reversed_lines(f_tmp):
  File "/home/xxx/binlog2sql/binlog2sql/binlog2sql_util.py", line 249, in reversed_lines
    block = block.decode("utf-8")
            ^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 0: invalid start byte
```

**Comment by QQfrown** [comment]
我之前也报这个错，但是我是在window运行的，然后我放到Linux就没问题了

**Comment by realcp1018** [comment]
用python2运行，python3对于多字节编码的字符串可能会遇到此类失败
