### ISSUE TITLE
使用时抛出异常

### ISSUE THREAD

**Issue by chariothy** [danfengcao/binlog2sql#39]
C:\projects\binlog2sql\binlog2sql>py binlog2sql.py -uuser -ppassword -h127.0.0.1 -P3306 --start-file="mysql-bin.001958"
Traceback (most recent call last):
  File "binlog2sql.py", line 150, in <module>
    binlog2sql.process_binlog()
  File "binlog2sql.py", line 107, in process_binlog
    row=row, flashback=self.flashback, e_start_pos=e_start_pos)
  File "C:\projects\binlog2sql\binlog2sql\binlog2sql_util.py", line 178, in concat_sql_from_binlog_event
    sql = cursor.mogrify(pattern['template'], pattern['values'])
  File "C:\Users\henry\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pymysql\cursors.py", line 143, in mogrify
    query = query % self._escape_args(args, conn)
  File "C:\Users\henry\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pymysql\cursors.py", line 118, in _escape_args
    return tuple(conn.literal(arg) for arg in args)
  File "C:\Users\henry\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pymysql\cursors.py", line 118, in <genexpr>
    return tuple(conn.literal(arg) for arg in args)
  File "C:\Users\henry\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pymysql\connections.py", line 821, in literal
    return self.escape(obj, self.encoders)
  File "C:\Users\henry\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pymysql\connections.py", line 814, in escape
    return escape_item(obj, self.charset, mapping=mapping)
  File "C:\Users\henry\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pymysql\converters.py", line 25, in escape_item
    val = encoder(val, charset, mapping)
  File "C:\Users\henry\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pymysql\converters.py", line 42, in escape_sequence
    return "(" + ",".join(n) + ")"
TypeError: sequence item 0: expected str instance, dict found

**Comment by moxwose** [comment]
解决了吗？，我也碰到了相同的问题。
