### ISSUE TITLE
为什么解析一段时间后就Lost connection to MySQL?

### ISSUE THREAD

**Issue by Fanduzi** [danfengcao/binlog2sql#41]
Traceback (most recent call last):
  File "binlog2sql.py", line 150, in <module>
    binlog2sql.process_binlog()
  File "binlog2sql.py", line 121, in process_binlog
    self.print_rollback_sql(filename=tmp_file)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 844, in __exit__
    self.commit()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 788, in commit
    self._read_ok_packet()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 767, in _read_ok_packet
    pkt = self._read_packet()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 987, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1033, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

**Comment by Fanduzi** [comment]
![image](https://user-images.githubusercontent.com/24428128/47948056-26792f80-df64-11e8-9b6e-3d5b876ff6e1.png)

**Comment by Fanduzi** [comment]
![image](https://user-images.githubusercontent.com/24428128/47948064-2da03d80-df64-11e8-8cfd-203b1f412436.png)
MySQL为Percona 5.7.14-7-log
