### ISSUE TITLE
工具对一个1.1M的2进制日志解析没到1/5 就报错

### ISSUE THREAD

**Issue by sundysundy** [danfengcao/binlog2sql#49]
UPDATE `manufacture`.`produce_task` SET `amount_product_planned`=200.000000, `workshop_id`=24, `amount_product_qualified`=143.000000, `start_time_planned`='2019-03-06 08:50:00', `project_code`='AWTP030267', `workgroup_id`=NULL, `project_product_code`='93312001', `config_scan_once`=0, `operator_ids`=('445'), `production_line_id`=0, `end_time_planned`='2019-03-07 08:50:00', `id`=34962, `process_group_name`=NULL, `attachment`=NULL, `operator_group_id`=NULL, `config_task_operator_exclusive`=0, `status`=2, `output_material_code`='91312010A', `task_code`=1903060005, `process_name`='卷膜（设备）', `origin_qc_passed`=1, `last_handover_operator_id`=NULL, `updated_at`='2019-03-07 10:25:57', `end_time_real`=NULL, `assigned_worker_ids`=('445'), `re_produce`=0, `process_seq`='2', `config_fifo`=1, `work_station_id`=273, `created_at`='2019-03-06 08:50:45', `org_id`=30, `start_time_real`='2019-03-06 08:58:11', `amount_product_faulty`=0.000000, `process_code`='21', `equipment_ids`=() WHERE `amount_product_planned`=200.000000 AND `workshop_id`=24 AND `amount_product_qualified`=142.000000 AND `start_time_planned`='2019-03-06 08:50:00' AND `project_code`='AWTP030267' AND `workgroup_id` IS NULL AND `project_product_code`='93312001' AND `config_scan_once`=0 AND `operator_ids`=('445') AND `production_line_id`=0 AND `end_time_planned`='2019-03-07 08:50:00' AND `id`=34962 AND `process_group_name` IS NULL AND `attachment` IS NULL AND `operator_group_id` IS NULL AND `config_task_operator_exclusive`=0 AND `status`=2 AND `output_material_code`='91312010A' AND `task_code`=1903060005 AND `process_name`='卷膜（设备' AND `origin_qc_passed`=1 AND `last_handover_operator_id` IS NULL AND `updated_at`='2019-03-07 09:57:57' AND `end_time_real` IS NULL AND `assigned_worker_ids`=('445') AND `re_produce`=0 AND `process_seq`='2' AND `config_fifo`=1 AND `work_station_id`=273 AND `created_at`='2019-03-06 08:50:45' AND `org_id`=30 AND `start_time_real`='2019-03-06 08:58:11' AND `amount_product_faulty`=0.000000 AND `process_code`='21' AND `equipment_ids`=() LIMIT 1; #start 349340245 end 349362132 time 2019-03-07 10:25:57
Traceback (most recent call last):
  File "binlog2sql.py", line 150, in <module>
    binlog2sql.process_binlog()
  File "binlog2sql.py", line 107, in process_binlog
    row=row, flashback=self.flashback, e_start_pos=e_start_pos)
  File "/usr/local/src/binlog2sql/binlog2sql/binlog2sql_util.py", line 178, in concat_sql_from_binlog_event
    sql = cursor.mogrify(pattern['template'], pattern['values'])
  File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 143, in mogrify
    query = query % self._escape_args(args, conn)
  File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 118, in _escape_args
    return tuple(conn.literal(arg) for arg in args)
  File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 118, in <genexpr>
    return tuple(conn.literal(arg) for arg in args)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 821, in literal
    return self.escape(obj, self.encoders)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 814, in escape
    return escape_item(obj, self.charset, mapping=mapping)
  File "/usr/lib/python2.7/site-packages/pymysql/converters.py", line 25, in escape_item
    val = encoder(val, charset, mapping)
  File "/usr/lib/python2.7/site-packages/pymysql/converters.py", line 42, in escape_sequence
    return "(" + ",".join(n) + ")"
TypeError: sequence item 0: expected string, dict found

**Comment by sundysundy** [comment]
有几个字段值是json 有没有可能是在这个的拼接引起的
