### ISSUE TITLE
解析正向SQL报错

### ISSUE THREAD

**Issue by EternalSpring** [danfengcao/binlog2sql#5]
Traceback (most recent call last):
  File "binlog2sql/binlog2sql.py", line 125, in <module>
    binlog2sql.process_binlog()
  File "binlog2sql/binlog2sql.py", line 70, in process_binlog
    for binlogevent in stream:
  File "/usr/lib/python2.6/site-packages/pymysqlreplication/binlogstream.py", line 370, in fetchone
    pkt = self._stream_connection._read_packet()
  File "/usr/lib/python2.6/site-packages/pymysql/connections.py", line 983, in _read_packet
    packet.check_error()
  File "/usr/lib/python2.6/site-packages/pymysql/connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python2.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1236, u'Could not open log file')
binlog文件500M，本地一两M的可以解析，连远程的mysql，文件大一点的就抛异常了。

**Comment by danfengcao** [comment]
猜测是mysql server参数设置的问题，查下这个参数是不是太小，调成1G试下，show variables like 'max_allowed_packet'; 仍有问题可以加我微信详细分析 danfeng053005

**Comment by danfengcao** [comment]
猜测是mysql server参数设置的问题，查下这个参数是不是太小，调成1G试下，show variables like 'max_allowed_packet'; 仍有问题可以加我微信详细分析 danfeng053005
