### ISSUE TITLE
mysql8.0.16 执行命令报错

### ISSUE THREAD

**Issue by 756613351** [danfengcao/binlog2sql#54]
python binlog2sql.py -h192.168.56.101 -P3306 -uroot -pXUq12  --start-file='binlog.000008'

Traceback (most recent call last):
  File "binlog2sql.py", line 152, in <module>
    back_interval=args.back_interval, only_dml=args.only_dml, sql_type=args.sql_type)
  File "binlog2sql.py", line 48, in __init__
    self.connection = pymysql.connect(**self.conn_setting)
  File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 706, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 931, in connect
    self._get_server_information()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1269, in _get_server_information
    self.server_charset = charset_by_id(lang).name
  File "/usr/local/lib/python2.7/site-packages/pymysql/charset.py", line 38, in by_id
    return self._by_id[id]
KeyError: 255

PyMySQL 0.7.11这个版本相对于mysql8以上的版低了，我更新到PyMySQL-0.9.3就可以了

**Comment by 5sdba** [comment]
我也是这种情况，我升级以后，解析标准SQL可以，解析回滚SQL解析出部分语句，然后显示
Traceback (most recent call last):
  File "binlog2sql.py", line 150, in <module>
    binlog2sql.process_binlog()
  File "binlog2sql.py", line 121, in process_binlog
    self.print_rollback_sql(filename=tmp_file)
  File "binlog2sql.py", line 129, in print_rollback_sql
    for line in reversed_lines(f_tmp):
  File "/database/binlog2sql/binlog2sql/binlog2sql_util.py", line 249, in reversed_lines
    block = block.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 0: invalid start byte

**Comment by miniminibox** [comment]
1). pymysql - 0.9.3
2).mysql-replication - 0.21
我之前也遇到这个问题,按照此版本装包即可解决

https://github.com/danfengcao/binlog2sql/issues/66
