### ISSUE TITLE
命令执行后错了

### ISSUE THREAD

**Issue by zoujd-github** [danfengcao/binlog2sql#57]
Traceback (most recent call last):
  File "binlog2sql.py", line 149, in <module>
    back_interval=args.back_interval, only_dml=args.only_dml, sql_type=args.sql_type)
  File "binlog2sql.py", line 47, in __init__
    with self.connection as cursor:
AttributeError: __exit__

**Comment by DarkFrank** [comment]
up.
![image](https://user-images.githubusercontent.com/38928727/219371213-ce351b7b-1fb8-4e02-8cac-14601e0abd87.png)

There is no such problem in python 2.
