### ISSUE TITLE
pymysql.err.InternalError: (1046, u'No database selected')

### ISSUE THREAD

**Issue by NorthernKnight** [danfengcao/binlog2sql#8]
# 环境：

- OS: CentOS 6.5 （阿里云主机）
- Python: 2.7.6
- MySQL: 5.6.16 （阿里云RDS）

# 终端执行命令：
`python binlog2sql.py -h10.10.10.10 -uusername -p'password' -P3306 -ddbname --start-file='mysql-bin.000789' > /tmp/raw.sql `

# 错误日志：
Traceback (most recent call last):
  File "binlog2sql.py", line 125, in <module>
    binlog2sql.process_binlog()
  File "binlog2sql.py", line 70, in process_binlog
    for binlogevent in stream:
  File "/usr/local/python2.7/lib/python2.7/site-packages/pymysqlreplication/binlogstream.py", line 391, in fetchone
    self.__freeze_schema)
  File "/usr/local/python2.7/lib/python2.7/site-packages/pymysqlreplication/packet.py", line 98, in __init__
    freeze_schema = freeze_schema)
  File "/usr/local/python2.7/lib/python2.7/site-packages/pymysqlreplication/row_event.py", line 542, in __init__
    self.column_schemas = self._ctl_connection._get_table_information(self.schema, self.table)
  File "/usr/local/python2.7/lib/python2.7/site-packages/pymysqlreplication/binlogstream.py", line 468, in __get_table_information
    """, (schema, table))
  File "/usr/local/python2.7/lib/python2.7/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/python2.7/lib/python2.7/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/python2.7/lib/python2.7/site-packages/pymysql/connections.py", line 837, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/python2.7/lib/python2.7/site-packages/pymysql/connections.py", line 1021, in _read_query_result
    result.read()
  File "/usr/local/python2.7/lib/python2.7/site-packages/pymysql/connections.py", line 1304, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/python2.7/lib/python2.7/site-packages/pymysql/connections.py", line 983, in _read_packet
    packet.check_error()
  File "/usr/local/python2.7/lib/python2.7/site-packages/pymysql/connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/python2.7/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1046, u'No database selected')

# 参数
log_bin	ON
server_id	8366
binlog_format	ROW
max_binlog_size	524288000

# 备注
并非解析每个binlog文件都会报该错误;
如果指定的数据库名称为不存在的数据库时反而不会报错，但解析出的sql中只有DDL而没有DML语句。

**Comment by NorthernKnight** [comment]
阿里云RDS数据库自身问题，重启实例后解决。

**Comment by mojie126** [comment]
我也遇到了，但是我们是生产数据库，不敢重启...
