### ISSUE TITLE
包找不到 我的mac自带了一个2.7的系统路径python，我自己安装了一个3.9 执行的时候出现了这个问题

### ISSUE THREAD

**Issue by sirius-il** [danfengcao/binlog2sql#86]
✗ python binlog2sql.py -h 127.0.0.1  -u root  --flashback -d sirius  -t t --start-file='binlog.000015' --start-pos=1238826 > ~/Desktop/flashback.sql

Traceback (most recent call last):
  File "/Users/pisces/Documents/python application/binlog2sql/binlog2sql/binlog2sql.py", line 7, in <module>
    from pymysqlreplication import BinLogStreamReader
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymysqlreplication/__init__.py", line 23, in <module>
    from .binlogstream import BinLogStreamReader
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymysqlreplication/binlogstream.py", line 8, in <module>
    from pymysql.util import int2byte
ModuleNotFoundError: No module named 'pymysql.util'

**Comment by michael-liumh** [comment]
用Python 3.8吧，3.8没问题

**Comment by raybon-lee** [comment]
可以用 pip3 install pymysql
